#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  Oct 28, 2025 10:57:37 AM CET  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 0
set vTcl(mode) Absolute
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #d9d9d9 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 988x749+320+263
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1711 1048
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    label "$top.lab48" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 24" -foreground #ff0000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "PyONMD 1.0" 
    vTcl:DefineAlias "$top.lab48" "Label1" vTcl:WidgetProc "Toplevel1" 1
    vTcl::widgets::ttk::notebook::createCmd "$top.tNo47" \
        -width 942 -height 604 
    vTcl:DefineAlias "$top.tNo47" "TNotebook1" vTcl:WidgetProc "Toplevel1" 1
    frame "$top.tNo47.t3" \
        -background #d9d9d9 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    vTcl:DefineAlias "$top.tNo47.t3" "TNotebook1_t4" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo47 add $top.tNo47.t3 \
        -padding 0 -sticky nsew -state normal -text "Convert & Create Movies" \
        -compound left -underline -1 
    set site_4_0  $top.tNo47.t3
    labelframe "$site_4_0.lab47" \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -text "Create Calibration Movie" -background #d9d9d9 -height 255 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 860 
    vTcl:DefineAlias "$site_4_0.lab47" "Labelframe2" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.lab47
    label "$site_5_0.lab52" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Background Intensity" 
    vTcl:DefineAlias "$site_5_0.lab52" "Label34" vTcl:WidgetProc "Toplevel1" 1
    label "$site_5_0.lab54" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Disp in pixel pro Frame" 
    vTcl:DefineAlias "$site_5_0.lab54" "Label35" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_5_0.ent60" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 84 
    vTcl:DefineAlias "$site_5_0.ent60" "Entry26" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_5_0.ent61" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 84 
    vTcl:DefineAlias "$site_5_0.ent61" "Entry27" vTcl:WidgetProc "Toplevel1" 1
    label "$site_5_0.lab56" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "th Frame " 
    vTcl:DefineAlias "$site_5_0.lab56" "Label37" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_5_0.ent62" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 44 
    vTcl:DefineAlias "$site_5_0.ent62" "Entry28" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_5_0.ent59" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 84 
    vTcl:DefineAlias "$site_5_0.ent59" "Entry25" vTcl:WidgetProc "Toplevel1" 1
    label "$site_5_0.lab51" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Particles Intensity" 
    vTcl:DefineAlias "$site_5_0.lab51" "Label33" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_5_0.ent58" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 84 
    vTcl:DefineAlias "$site_5_0.ent58" "Entry24" vTcl:WidgetProc "Toplevel1" 1
    label "$site_5_0.lab50" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Particles Area" 
    vTcl:DefineAlias "$site_5_0.lab50" "Label32" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_5_0.ent57" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 84 
    vTcl:DefineAlias "$site_5_0.ent57" "Entry23" vTcl:WidgetProc "Toplevel1" 1
    label "$site_5_0.lab49" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Particles Nb" 
    vTcl:DefineAlias "$site_5_0.lab49" "Label31" vTcl:WidgetProc "Toplevel1" 1
    label "$site_5_0.lab55" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Modif Disp Dir Every " 
    vTcl:DefineAlias "$site_5_0.lab55" "Label36" vTcl:WidgetProc "Toplevel1" 1
    button "$site_5_0.but48" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "f_Create_Movie" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Create Movie" 
    vTcl:DefineAlias "$site_5_0.but48" "Button22" vTcl:WidgetProc "Toplevel1" 1
    label "$site_5_0.lab47" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Create Calibration Movie Called Disks_Movie in the PGM Folder" 
    vTcl:DefineAlias "$site_5_0.lab47" "Label20" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.lab52 \
        -in $site_5_0 -x 20 -y 110 -anchor nw -bordermode ignore 
    place $site_5_0.lab54 \
        -in $site_5_0 -x 280 -y 110 -anchor nw -bordermode ignore 
    place $site_5_0.ent60 \
        -in $site_5_0 -x 180 -y 110 -width 84 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent61 \
        -in $site_5_0 -x 450 -y 110 -width 84 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab56 \
        -in $site_5_0 -x 770 -y 110 -anchor nw -bordermode ignore 
    place $site_5_0.ent62 \
        -in $site_5_0 -x 710 -y 110 -width 44 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent59 \
        -in $site_5_0 -x 670 -y 40 -width 84 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab51 \
        -in $site_5_0 -x 540 -y 40 -anchor nw -bordermode ignore 
    place $site_5_0.ent58 \
        -in $site_5_0 -x 450 -y 40 -width 84 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab50 \
        -in $site_5_0 -x 350 -y 40 -anchor nw -bordermode ignore 
    place $site_5_0.ent57 \
        -in $site_5_0 -x 180 -y 40 -width 84 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab49 \
        -in $site_5_0 -x 80 -y 40 -width 94 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab55 \
        -in $site_5_0 -x 560 -y 110 -anchor nw -bordermode ignore 
    place $site_5_0.but48 \
        -in $site_5_0 -x 20 -y 180 -width 207 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab47 \
        -in $site_5_0 -x 250 -y 180 -width 464 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    label "$site_4_0.lab50" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "the converted file will be saved in that folder" 
    vTcl:DefineAlias "$site_4_0.lab50" "Label13" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_0.lab49" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Select folder with H264 file and push Covert button" 
    vTcl:DefineAlias "$site_4_0.lab49" "Label12" vTcl:WidgetProc "Toplevel1" 1
    button "$site_4_0.but48" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "f_ConvertMovie_1" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Convert h264 to avi" 
    vTcl:DefineAlias "$site_4_0.but48" "Button10" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_0.lab51" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Specify path to FFMPEG.exe" 
    vTcl:DefineAlias "$site_4_0.lab51" "Label38" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_4_0.ent47" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 824 
    vTcl:DefineAlias "$site_4_0.ent47" "Entry29" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab47 \
        -in $site_4_0 -x 40 -y 200 -width 860 -relwidth 0 -height 255 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab50 \
        -in $site_4_0 -x 310 -y 150 -width 354 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab49 \
        -in $site_4_0 -x 310 -y 120 -width 384 -relwidth 0 -height 41 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but48 \
        -in $site_4_0 -x 60 -y 130 -width 217 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab51 \
        -in $site_4_0 -x 70 -y 20 -width 204 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent47 \
        -in $site_4_0 -x 60 -y 60 -width 824 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame "$top.tNo47.t0" \
        -background #d9d9d9 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    vTcl:DefineAlias "$top.tNo47.t0" "TNotebook1_t1" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo47 add $top.tNo47.t0 \
        -padding 0 -sticky nsew -state normal -text "Select Movie" \
        -compound left -underline -1 
    set site_4_1  $top.tNo47.t0
    entry "$site_4_1.ent52" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -textvariable "entryNthFrame" -width 124 
    vTcl:DefineAlias "$site_4_1.ent52" "Entry3" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_1.lab51" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "N th Frame" 
    vTcl:DefineAlias "$site_4_1.lab51" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_1.lab50" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground black \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "The Movie Contains" 
    vTcl:DefineAlias "$site_4_1.lab50" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_1.lab53" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground black \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Frames" 
    vTcl:DefineAlias "$site_4_1.lab53" "Label7" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_4_1.ent50" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -textvariable "entryName" -width 574 
    vTcl:DefineAlias "$site_4_1.ent50" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_1.lab49" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Name" 
    vTcl:DefineAlias "$site_4_1.lab49" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_1.lab56" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Keep Movie From Frame" 
    vTcl:DefineAlias "$site_4_1.lab56" "Label18" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_1.lab57" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "To " 
    vTcl:DefineAlias "$site_4_1.lab57" "Label19" vTcl:WidgetProc "Toplevel1" 1
    button "$site_4_1.but48" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "f_Check_Mov_Illum_Stab" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Check Movie Illumination Stability" 
    vTcl:DefineAlias "$site_4_1.but48" "Button16" vTcl:WidgetProc "Toplevel1" 1
    button "$site_4_1.but49" \
        -activebackground #d9d9d9 -activeforeground black -background #00ffff \
        -command "f_Button_1" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Display n th Frame" 
    vTcl:DefineAlias "$site_4_1.but49" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button "$site_4_1.but47" \
        -activebackground #d9d9d9 -activeforeground black -background #00ffff \
        -command "f_DispFirstMinLast" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Display First - Last Frame" 
    vTcl:DefineAlias "$site_4_1.but47" "Button4" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_4_1.ent54" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -textvariable "MovieBegin" -width 84 
    vTcl:DefineAlias "$site_4_1.ent54" "Entry13" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_4_1.ent55" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -textvariable "MovieEnd" -width 84 
    vTcl:DefineAlias "$site_4_1.ent55" "Entry14" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_4_1.ent48" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -textvariable "entryPath" -width 574 
    vTcl:DefineAlias "$site_4_1.ent48" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_1.lab47" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Path" 
    vTcl:DefineAlias "$site_4_1.lab47" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_1.lab52" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #008000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -textvariable "nTotalFrames" 
    vTcl:DefineAlias "$site_4_1.lab52" "Label6" vTcl:WidgetProc "Toplevel1" 1
    button "$site_4_1.but58" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "f_Reduce_Movie" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Reduce Movie" 
    vTcl:DefineAlias "$site_4_1.but58" "Button17" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_1.ent52 \
        -in $site_4_1 -x 120 -y 150 -width 124 -relwidth 0 -height 40 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.lab51 \
        -in $site_4_1 -x 20 -y 150 -width 99 -relwidth 0 -height 40 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.lab50 \
        -in $site_4_1 -x 280 -y 150 -width 185 -relwidth 0 -height 40 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.lab53 \
        -in $site_4_1 -x 570 -y 150 -width 74 -relwidth 0 -height 40 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.ent50 \
        -in $site_4_1 -x 80 -y 90 -width 574 -relwidth 0 -height 40 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.lab49 \
        -in $site_4_1 -x 20 -y 90 -width 56 -relwidth 0 -height 40 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.lab56 \
        -in $site_4_1 -x 40 -y 370 -width 174 -relwidth 0 -height 41 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.lab57 \
        -in $site_4_1 -x 320 -y 370 -width 34 -relwidth 0 -height 41 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.but48 \
        -in $site_4_1 -x 40 -y 290 -width 267 -relwidth 0 -height 46 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.but49 \
        -in $site_4_1 -x 40 -y 220 -width 277 -relwidth 0 -height 46 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.but47 \
        -in $site_4_1 -x 380 -y 220 -width 277 -relwidth 0 -height 46 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.ent54 \
        -in $site_4_1 -x 230 -y 370 -width 84 -relwidth 0 -height 40 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.ent55 \
        -in $site_4_1 -x 370 -y 370 -width 84 -relwidth 0 -height 40 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.ent48 \
        -in $site_4_1 -x 80 -y 30 -width 574 -relwidth 0 -height 40 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.lab47 \
        -in $site_4_1 -x 20 -y 30 -width 0 -relwidth 0.065 -height 0 \
        -relheight 0.06 -anchor nw -bordermode ignore 
    place $site_4_1.lab52 \
        -in $site_4_1 -x 460 -y 150 -width 84 -relwidth 0 -height 40 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.but58 \
        -in $site_4_1 -x 480 -y 370 -width 177 -relwidth 0 -height 46 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame "$top.tNo47.t1" \
        -background #d9d9d9 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    vTcl:DefineAlias "$top.tNo47.t1" "TNotebook1_t2" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo47 add $top.tNo47.t1 \
        -padding 0 -sticky nsew -state normal \
        -text "Original Image Processing" -compound left -underline -1 
    set site_4_2  $top.tNo47.t1
    entry "$site_4_2.ent50" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -textvariable "MedianFilterSize" -width 74 
    vTcl:DefineAlias "$site_4_2.ent50" "Entry5" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_4_2.ent48" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -textvariable "FudgeFactor" -width 74 
    vTcl:DefineAlias "$site_4_2.ent48" "Entry4" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_2.lab47" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Fudge Factor" 
    vTcl:DefineAlias "$site_4_2.lab47" "Label8" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_2.lab49" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Median Filter Size" 
    vTcl:DefineAlias "$site_4_2.lab49" "Label9" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_2.lab50" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Kernel Size" 
    vTcl:DefineAlias "$site_4_2.lab50" "Label10" vTcl:WidgetProc "Toplevel1" 1
    button "$site_4_2.but50" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "f_DetectCells" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Detect Cells" 
    vTcl:DefineAlias "$site_4_2.but50" "Button2" vTcl:WidgetProc "Toplevel1" 1
    button "$site_4_2.but51" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "f_AppMedFilt" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Apply Median Filter" 
    vTcl:DefineAlias "$site_4_2.but51" "Button5" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_2.lab51" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Erosion Cycles" 
    vTcl:DefineAlias "$site_4_2.lab51" "Label10_1" vTcl:WidgetProc "Toplevel1" 1
    button "$site_4_2.but47" \
        -activebackground #d9d9d9 -activeforeground black -background #00ffff \
        -command "f_Acpt_Filt_Img" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Accept Filtered Image" 
    vTcl:DefineAlias "$site_4_2.but47" "Button6" vTcl:WidgetProc "Toplevel1" 1
    button "$site_4_2.but54" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "f_Erode" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Erode" 
    vTcl:DefineAlias "$site_4_2.but54" "Button7" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_4_2.ent53" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -textvariable "ErodCycles" -width 74 
    vTcl:DefineAlias "$site_4_2.ent53" "Entry7" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_4_2.ent52" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -textvariable "DilErKernSize" -width 74 
    vTcl:DefineAlias "$site_4_2.ent52" "Entry6" vTcl:WidgetProc "Toplevel1" 1
    button "$site_4_2.but52" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "f_OrigImMaskFillHoles" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Fill Holes" 
    vTcl:DefineAlias "$site_4_2.but52" "Button28" vTcl:WidgetProc "Toplevel1" 1
    button "$site_4_2.but48" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "f_Disp_Blob_Area" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Display Blobs Area" 
    vTcl:DefineAlias "$site_4_2.but48" "Button8_1" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_4_2.ent54" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 74 
    vTcl:DefineAlias "$site_4_2.ent54" "Entry9" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_2.lab56" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "And" 
    vTcl:DefineAlias "$site_4_2.lab56" "Label11_1" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_4_2.ent57" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 74 
    vTcl:DefineAlias "$site_4_2.ent57" "Entry10" vTcl:WidgetProc "Toplevel1" 1
    button "$site_4_2.but59" \
        -activebackground #d9d9d9 -activeforeground black -background #00ffff \
        -command "f_Acpt_Blobs" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Accept Blobs" 
    vTcl:DefineAlias "$site_4_2.but59" "Button9_1" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_2.lab53" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Keep Blobs Between" 
    vTcl:DefineAlias "$site_4_2.lab53" "Label11" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_2.lab52" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Press q when done" 
    vTcl:DefineAlias "$site_4_2.lab52" "Label14" vTcl:WidgetProc "Toplevel1" 1
    button "$site_4_2.but49" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "f_SetRoiToO" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Set ROI to 0" 
    vTcl:DefineAlias "$site_4_2.but49" "Button11" vTcl:WidgetProc "Toplevel1" 1
    button "$site_4_2.but53" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "f_CrossSectOrig" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Cross Section" 
    vTcl:DefineAlias "$site_4_2.but53" "Button32" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_2.lab54" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Select Intensities Between" 
    vTcl:DefineAlias "$site_4_2.lab54" "Label29" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_4_2.ent55" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 64 
    vTcl:DefineAlias "$site_4_2.ent55" "Entry21" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_2.lab57" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "And" 
    vTcl:DefineAlias "$site_4_2.lab57" "Label30" vTcl:WidgetProc "Toplevel1" 1
    button "$site_4_2.but60" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "f_SelectByThresholding" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Select by Thresholding" 
    vTcl:DefineAlias "$site_4_2.but60" "Button33" vTcl:WidgetProc "Toplevel1" 1
    button "$site_4_2.but58" \
        -activebackground #d9d9d9 -activeforeground black -background #00ffff \
        -command "f_Acpt_Mask" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Accept Mask" 
    vTcl:DefineAlias "$site_4_2.but58" "Button9" vTcl:WidgetProc "Toplevel1" 1
    button "$site_4_2.but57" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "f_Dilate" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Dilate" 
    vTcl:DefineAlias "$site_4_2.but57" "Button8" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_4_2.ent56" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -textvariable "DilateCycles" -width 74 
    vTcl:DefineAlias "$site_4_2.ent56" "Entry8" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_2.lab55" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Dilatation Cycles" 
    vTcl:DefineAlias "$site_4_2.lab55" "Label10_1_1" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_4_2.ent58" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 64 
    vTcl:DefineAlias "$site_4_2.ent58" "Entry22" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_2.ent50 \
        -in $site_4_2 -x 200 -y 30 -width 74 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.ent48 \
        -in $site_4_2 -x 200 -y 80 -width 74 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.lab47 \
        -in $site_4_2 -x 90 -y 80 -width 104 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.lab49 \
        -in $site_4_2 -x 60 -y 30 -width 144 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.lab50 \
        -in $site_4_2 -x 100 -y 140 -width 94 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.but50 \
        -in $site_4_2 -x 300 -y 80 -width 197 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.but51 \
        -in $site_4_2 -x 300 -y 30 -width 197 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.lab51 \
        -in $site_4_2 -x 300 -y 140 -width 114 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.but47 \
        -in $site_4_2 -x 530 -y 30 -width 177 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.but54 \
        -in $site_4_2 -x 530 -y 140 -width 177 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.ent53 \
        -in $site_4_2 -x 420 -y 140 -width 74 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_4_2.ent52 \
        -in $site_4_2 -x 200 -y 140 -width 74 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.but52 \
        -in $site_4_2 -x 530 -y 80 -width 167 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.but48 \
        -in $site_4_2 -x 70 -y 460 -width 197 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.ent54 \
        -in $site_4_2 -x 290 -y 460 -width 74 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.lab56 \
        -in $site_4_2 -x 370 -y 460 -width 44 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.ent57 \
        -in $site_4_2 -x 420 -y 460 -width 74 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.but59 \
        -in $site_4_2 -x 520 -y 460 -width 177 -height 36 -anchor nw \
        -bordermode ignore 
    place $site_4_2.lab53 \
        -in $site_4_2 -x 330 -y 420 -width 154 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.lab52 \
        -in $site_4_2 -x 290 -y 380 -width 144 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.but49 \
        -in $site_4_2 -x 70 -y 380 -width 197 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.but53 \
        -in $site_4_2 -x 70 -y 270 -width 197 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.lab54 \
        -in $site_4_2 -x 300 -y 230 -width 204 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.ent55 \
        -in $site_4_2 -x 300 -y 270 -width 64 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.lab57 \
        -in $site_4_2 -x 380 -y 280 -width 44 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.but60 \
        -in $site_4_2 -x 530 -y 270 -width 177 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.but58 \
        -in $site_4_2 -x 530 -y 330 -width 177 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.but57 \
        -in $site_4_2 -x 530 -y 190 -width 177 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.ent56 \
        -in $site_4_2 -x 420 -y 190 -width 74 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_4_2.lab55 \
        -in $site_4_2 -x 280 -y 190 -width 124 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.ent58 \
        -in $site_4_2 -x 430 -y 270 -width 64 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame "$top.tNo47.t2" \
        -background #d9d9d9 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    vTcl:DefineAlias "$top.tNo47.t2" "TNotebook1_t3" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo47 add $top.tNo47.t2 \
        -padding 0 -sticky nsew -state normal -text "Original Image Analysis" \
        -compound left -underline -1 
    set site_4_3  $top.tNo47.t2
    button "$site_4_3.but51" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "f_Blob_Analysis" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Blob Analysis" 
    vTcl:DefineAlias "$site_4_3.but51" "Button3" vTcl:WidgetProc "Toplevel1" 1
    labelframe "$site_4_3.lab47" \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -text "Original Image Analysis After Watershade Segmentation" \
        -background #d9d9d9 -height 115 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -width 700 
    vTcl:DefineAlias "$site_4_3.lab47" "Labelframe5" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_3.lab47
    label "$site_5_0.lab49" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Min Dist For Peak Detection" 
    vTcl:DefineAlias "$site_5_0.lab49" "Label28" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_5_0.ent50" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 114 
    vTcl:DefineAlias "$site_5_0.ent50" "Entry20" vTcl:WidgetProc "Toplevel1" 1
    button "$site_5_0.but51" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "f_Watershade_Seg" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Blob Analysis After Segmentation" 
    vTcl:DefineAlias "$site_5_0.but51" "Button31" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.lab49 \
        -in $site_5_0 -x 20 -y 50 -width 204 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent50 \
        -in $site_5_0 -x 230 -y 50 -width 114 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.but51 \
        -in $site_5_0 -x 390 -y 50 -width 267 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_3.but51 \
        -in $site_4_3 -x 40 -y 50 -width 137 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_3.lab47 \
        -in $site_4_3 -x 50 -y 130 -width 700 -relwidth 0 -height 115 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame "$top.tNo47.t4" \
        -background #d9d9d9 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    vTcl:DefineAlias "$top.tNo47.t4" "TNotebook1_t5" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo47 add $top.tNo47.t4 \
        -padding 0 -sticky nsew -state normal -text "Create Diff Image" \
        -compound left -underline -1 
    set site_4_4  $top.tNo47.t4
    label "$site_4_4.lab49" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Delta Frame" 
    vTcl:DefineAlias "$site_4_4.lab49" "Label15" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_4_4.ent47" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 84 
    vTcl:DefineAlias "$site_4_4.ent47" "Entry11" vTcl:WidgetProc "Toplevel1" 1
    button "$site_4_4.but50" \
        -activebackground #d9d9d9 -activeforeground black -background #00ffff \
        -command "f_CreateDiffImg" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Create Diff Image" 
    vTcl:DefineAlias "$site_4_4.but50" "Button12" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_4.lab49 \
        -in $site_4_4 -x 30 -y 60 -width 104 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_4.ent47 \
        -in $site_4_4 -x 140 -y 60 -width 84 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_4.but50 \
        -in $site_4_4 -x 250 -y 60 -width 157 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame "$top.tNo47.t5" \
        -background #d9d9d9 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    vTcl:DefineAlias "$top.tNo47.t5" "TNotebook1_t6" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo47 add $top.tNo47.t5 \
        -padding 0 -sticky nsew -state normal -text "Diff Image Processing" \
        -compound left -underline -1 
    set site_4_5  $top.tNo47.t5
    button "$site_4_5.but47" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "f_Cross_Section" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Cross Section" 
    vTcl:DefineAlias "$site_4_5.but47" "Button13" vTcl:WidgetProc "Toplevel1" 1
    labelframe "$site_4_5.lab58" \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -text "Create Diff Image Mask" -background #d9d9d9 -height 315 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 740 
    vTcl:DefineAlias "$site_4_5.lab58" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_5.lab58
    label "$site_5_0.lab64" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Kernel Size" 
    vTcl:DefineAlias "$site_5_0.lab64" "Label20_2" vTcl:WidgetProc "Toplevel1" 1
    label "$site_5_0.lab66" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Erosion Cycles" 
    vTcl:DefineAlias "$site_5_0.lab66" "Label20_1" vTcl:WidgetProc "Toplevel1" 1
    label "$site_5_0.lab69" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Dilatation Cycles" 
    vTcl:DefineAlias "$site_5_0.lab69" "Label20_1_1" vTcl:WidgetProc "Toplevel1" 1
    label "$site_5_0.lab61" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Threshold Level" 
    vTcl:DefineAlias "$site_5_0.lab61" "Label21" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_5_0.ent65" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 74 
    vTcl:DefineAlias "$site_5_0.ent65" "Entry15" vTcl:WidgetProc "Toplevel1" 1
    button "$site_5_0.but71" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "f_DilDiff" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Dilate" 
    vTcl:DefineAlias "$site_5_0.but71" "Button19" vTcl:WidgetProc "Toplevel1" 1
    button "$site_5_0.but68" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "f_ErodeDiff" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Erode" 
    vTcl:DefineAlias "$site_5_0.but68" "Button18" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_5_0.ent67" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 74 
    vTcl:DefineAlias "$site_5_0.ent67" "Entry16" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_5_0.ent62" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -textvariable "difImgThreshold" -width 94 
    vTcl:DefineAlias "$site_5_0.ent62" "Entry12" vTcl:WidgetProc "Toplevel1" 1
    button "$site_5_0.but63" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "f_Set_Dif_Img_Thresh" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Set Dif Img Threshold" 
    vTcl:DefineAlias "$site_5_0.but63" "Button15" vTcl:WidgetProc "Toplevel1" 1
    button "$site_5_0.but47" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "f_fill_blob_holes" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Fill Blobs Holes" 
    vTcl:DefineAlias "$site_5_0.but47" "Button21" vTcl:WidgetProc "Toplevel1" 1
    button "$site_5_0.but48" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "f_Disp_Dif_Blob_Area" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Display Blobs Area" 
    vTcl:DefineAlias "$site_5_0.but48" "Button25" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_5_0.ent70" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 74 
    vTcl:DefineAlias "$site_5_0.ent70" "Entry17" vTcl:WidgetProc "Toplevel1" 1
    label "$site_5_0.lab49" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Keep Blobs Between" 
    vTcl:DefineAlias "$site_5_0.lab49" "Label26" vTcl:WidgetProc "Toplevel1" 1
    label "$site_5_0.lab52" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "And" 
    vTcl:DefineAlias "$site_5_0.lab52" "Label27" vTcl:WidgetProc "Toplevel1" 1
    button "$site_5_0.but72" \
        -activebackground #d9d9d9 -activeforeground black -background #00ffff \
        -command "f_AcceptDiffImgMask" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Accept Mask" 
    vTcl:DefineAlias "$site_5_0.but72" "Button20" vTcl:WidgetProc "Toplevel1" 1
    button "$site_5_0.but54" \
        -activebackground #d9d9d9 -activeforeground black -background #00ffff \
        -command "f_Accept_Diff_Blobs" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Accept Blobs" 
    vTcl:DefineAlias "$site_5_0.but54" "Button26" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_5_0.ent51" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 74 
    vTcl:DefineAlias "$site_5_0.ent51" "Entry18" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_5_0.ent53" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 74 
    vTcl:DefineAlias "$site_5_0.ent53" "Entry19" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.lab64 \
        -in $site_5_0 -x 20 -y 110 -width 94 -height 31 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab66 \
        -in $site_5_0 -x 220 -y 110 -width 114 -height 31 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab69 \
        -in $site_5_0 -x 200 -y 160 -width 124 -height 31 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab61 \
        -in $site_5_0 -x 120 -y 40 -width 124 -height 31 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent65 \
        -in $site_5_0 -x 120 -y 110 -width 74 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_5_0.but71 \
        -in $site_5_0 -x 440 -y 160 -width 117 -height 36 -anchor nw \
        -bordermode ignore 
    place $site_5_0.but68 \
        -in $site_5_0 -x 440 -y 110 -width 117 -height 36 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent67 \
        -in $site_5_0 -x 340 -y 110 -width 74 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent62 \
        -in $site_5_0 -x 260 -y 40 -width 94 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.but63 \
        -in $site_5_0 -x 370 -y 40 -width 187 -height 36 -anchor nw \
        -bordermode ignore 
    place $site_5_0.but47 \
        -in $site_5_0 -x 580 -y 40 -width 137 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.but48 \
        -in $site_5_0 -x 20 -y 240 -width 167 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent70 \
        -in $site_5_0 -x 340 -y 160 -width 74 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab49 \
        -in $site_5_0 -x 260 -y 210 -width 154 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab52 \
        -in $site_5_0 -x 290 -y 240 -width 44 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.but72 \
        -in $site_5_0 -x 580 -y 110 -width 137 -relwidth 0 -height 86 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.but54 \
        -in $site_5_0 -x 440 -y 240 -width 277 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent51 \
        -in $site_5_0 -x 210 -y 240 -width 74 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent53 \
        -in $site_5_0 -x 340 -y 240 -width 74 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_5.but47 \
        -in $site_4_5 -x 60 -y 40 -width 167 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_5.lab58 \
        -in $site_4_5 -x 50 -y 100 -width 740 -relwidth 0 -height 315 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame "$top.tNo47.t6" \
        -background #d9d9d9 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    vTcl:DefineAlias "$top.tNo47.t6" "TNotebook1_t7" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo47 add $top.tNo47.t6 \
        -padding 0 -sticky nsew -state normal -text "Diff Image Analysis" \
        -compound left -underline -1 
    set site_4_6  $top.tNo47.t6
    label "$site_4_6.lab47" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Unmasked Diff Image Tot Pixels per Frames" 
    vTcl:DefineAlias "$site_4_6.lab47" "Label16" vTcl:WidgetProc "Toplevel1" 1
    button "$site_4_6.but50" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "f_Calc_Diff_Im_Tot_Pix" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Calculate Diff Image Total Pixels" 
    vTcl:DefineAlias "$site_4_6.but50" "Button14" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_6.lab49" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #008080 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -textvariable "unMaskDifTotPix" 
    vTcl:DefineAlias "$site_4_6.lab49" "Label17" vTcl:WidgetProc "Toplevel1" 1
    labelframe "$site_4_6.lab50" \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -text "Background Analysis" -background #d9d9d9 -height 165 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 780 
    vTcl:DefineAlias "$site_4_6.lab50" "Labelframe3" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_6.lab50
    label "$site_5_0.lab47" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "BckGd Average Val" 
    vTcl:DefineAlias "$site_5_0.lab47" "Label22" vTcl:WidgetProc "Toplevel1" 1
    button "$site_5_0.but51" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "f_Ana_Bckgd" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Background Without Blobs" 
    vTcl:DefineAlias "$site_5_0.but51" "Button23" vTcl:WidgetProc "Toplevel1" 1
    label "$site_5_0.lab51" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "ROI Def Avrg Val" 
    vTcl:DefineAlias "$site_5_0.lab51" "Label25" vTcl:WidgetProc "Toplevel1" 1
    button "$site_5_0.but47" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "f_ana_ROI_Bckgnd" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "ROI defined Background" 
    vTcl:DefineAlias "$site_5_0.but47" "Button24" vTcl:WidgetProc "Toplevel1" 1
    label "$site_5_0.lab50" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "std" 
    vTcl:DefineAlias "$site_5_0.lab50" "Label24" vTcl:WidgetProc "Toplevel1" 1
    label "$site_5_0.lab55" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "std" 
    vTcl:DefineAlias "$site_5_0.lab55" "Label24_2" vTcl:WidgetProc "Toplevel1" 1
    label "$site_5_0.lab52" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #008080 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -textvariable "roi_bck_Av_Val" 
    vTcl:DefineAlias "$site_5_0.lab52" "Label23_2" vTcl:WidgetProc "Toplevel1" 1
    label "$site_5_0.lab49" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #008080 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -textvariable "bck_Av_Val" 
    vTcl:DefineAlias "$site_5_0.lab49" "Label23" vTcl:WidgetProc "Toplevel1" 1
    label "$site_5_0.lab53" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #008080 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -textvariable "bck_Std_Val" 
    vTcl:DefineAlias "$site_5_0.lab53" "Label23_1" vTcl:WidgetProc "Toplevel1" 1
    label "$site_5_0.lab56" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #008080 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -textvariable "roi_bck_Std_Val" 
    vTcl:DefineAlias "$site_5_0.lab56" "Label23_1_1" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.lab47 \
        -in $site_5_0 -x 310 -y 40 -width 144 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.but51 \
        -in $site_5_0 -x 30 -y 40 -width 257 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab51 \
        -in $site_5_0 -x 310 -y 100 -width 134 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.but47 \
        -in $site_5_0 -x 30 -y 100 -width 257 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab50 \
        -in $site_5_0 -x 560 -y 40 -width 44 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab55 \
        -in $site_5_0 -x 560 -y 100 -width 44 -height 31 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab52 \
        -in $site_5_0 -x 460 -y 100 -width 94 -height 31 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab49 \
        -in $site_5_0 -x 460 -y 40 -width 94 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab53 \
        -in $site_5_0 -x 600 -y 40 -width 94 -height 31 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab56 \
        -in $site_5_0 -x 610 -y 100 -width 94 -height 31 -anchor nw \
        -bordermode ignore 
    labelframe "$site_4_6.lab51" \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -text "Diff Blob Analysis" -background #d9d9d9 -height 175 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 780 
    vTcl:DefineAlias "$site_4_6.lab51" "Labelframe4" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_6.lab51
    button "$site_5_0.but52" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "f_Anal_Diff_Blobs" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Analyze Diff Blobs" 
    vTcl:DefineAlias "$site_5_0.but52" "Button27" vTcl:WidgetProc "Toplevel1" 1
    label "$site_5_0.lab47" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Number Of Violins / Blob" 
    vTcl:DefineAlias "$site_5_0.lab47" "Label39" vTcl:WidgetProc "Toplevel1" 1
    button "$site_5_0.but47" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "f_Ana_Blob_f_Time" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Analyze Blobs = f(t)" 
    vTcl:DefineAlias "$site_5_0.but47" "Button29" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_5_0.ent48" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 64 
    vTcl:DefineAlias "$site_5_0.ent48" "Entry30" vTcl:WidgetProc "Toplevel1" 1
    button "$site_5_0.but48" \
        -activebackground #d9d9d9 -activeforeground black -background #00ff00 \
        -command "f_Parameters_Explanation" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Parameters Explanantion" 
    vTcl:DefineAlias "$site_5_0.but48" "Button30" vTcl:WidgetProc "Toplevel1" 1
    button "$site_5_0.but49" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "f_ViolinPlots" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Display Violin Plots" 
    vTcl:DefineAlias "$site_5_0.but49" "Button34" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.but52 \
        -in $site_5_0 -x 20 -y 40 -width 247 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab47 \
        -in $site_5_0 -x 300 -y 100 -width 194 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.but47 \
        -in $site_5_0 -x 20 -y 100 -width 247 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent48 \
        -in $site_5_0 -x 490 -y 100 -width 64 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.but48 \
        -in $site_5_0 -x 290 -y 40 -width 197 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.but49 \
        -in $site_5_0 -x 580 -y 90 -width 187 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_6.lab47 \
        -in $site_4_6 -x 50 -y 110 -width 314 -relwidth 0 -height 41 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_6.but50 \
        -in $site_4_6 -x 60 -y 40 -width 277 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_6.lab49 \
        -in $site_4_6 -x 380 -y 110 -width 154 -relwidth 0 -height 41 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_6.lab50 \
        -in $site_4_6 -x 60 -y 170 -width 780 -relwidth 0 -height 165 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_6.lab51 \
        -in $site_4_6 -x 60 -y 360 -width 780 -relwidth 0 -height 175 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab48 \
        -in $top -x 370 -y 20 -width 207 -relwidth 0 -height 42 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tNo47 \
        -in $top -x 30 -y 90 -width 942 -relwidth 0 -height 604 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

